spring.application.name=GGarciaPruebaTecnica
# Servidor
server.port=8080
 
# Zona horaria (usada en UserService para created_at)
app.timezone=Indian/Antananarivo
 
# Clave AES-256 para cifrar/descifrar passwords: 32 bytes en Base64
app.aes.secret=dGhpcyBpcyBhIDMyLWJ5dGUgc2VjcmV0IGtleXMhISE=
 
# Spring MVC
spring.mvc.problemdetails.enabled=false
 
# JWT
app.jwt.secret=e87e19b6edc82b8b51a520b08bb871b9176ad4da01e24d003c8871e4759ea1b5
app.jwt.expiration-ms=3600000