spring.application.name=GGarciaPruebaTecnica
# Servidor
server.port=8080

# Zona horaria de Madagascar para created_at
app.timezone=Indian/Antananarivo

# Clave AES-256: 32 bytes en Base64
app.aes.secret=dGhpcyBpcyBhIDMyLWJ5dGUgc2VjcmV0IGtleXMhISE=